only_physical = true
use_fstab = false
disks_filter = "/sysroot /boot /boot/efi"
io_mode = true
io_graph_combined = true
theme = "kanagawa-wave"
cpu_graph_lower = "user"
cpu_graph_upper = "total"
cpu_invert_lower = true
freq_mode = "highest"
