name: Build VM Image
on:
  push:
    tags:
      - '**'
    branches:
      - build/**
    paths:
      - packages/**
      - config/bootc.vm.toml
      - config/images.common.lst
      - config/images.vm.lst
      - config/packages.common.lst
      - config/packages.vm.lst
      - root/**
      - Containerfile
      - .github/workflows/build-vm.yaml

env:
  REGISTRY: ghcr.io/tao-ce/cozy
  FS_TYPE: btrfs
  FEDORA_VERSION: "44"
  IMAGE_PFX: tao-ce-cozy-vm-

jobs:
  build:
    strategy:
      matrix:
        include:
        - fedora_flavor: quay.io/fedora/fedora-bootc
          name: server
        # - fedora_flavor: quay.io/fedora-ostree-desktops/kinoite
          # name: desktop
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-24.04

    steps:
    - name: Tar as root (setuid bit)
      run: |
        sudo chmod u+s /usr/bin/tar

    - name: Checkout code
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Setup cache
      uses: actions/cache@v5
      with:
        path: /var/lib/containers/storage
        key: ${{ runner.os }}-${{ runner.arch }}-containers-storage

    - name: Build Image
      run: |
        sudo buildah build \
          -t ${{ env.REGISTRY }}/vm/${{ matrix.name }}:latest \
          --build-arg FEDORA_FLAVOR=${{ matrix.fedora_flavor }} \
          --build-arg FEDORA_VERSION=${{ env.FEDORA_VERSION }} \
          --build-arg MEDIUM=vm \
          --target appliance \
          --network=host \
          .

    - name: Build VM Image
      run: |
        mkdir -p output/${{ matrix.name }}
        sudo podman run \
          --rm \
          -it \
          --privileged \
          --security-opt label=type:unconfined_t \
          -v ./config/bootc.vm.toml:/config.toml:ro \
          -v ./output/${{ matrix.name }}:/output \
          -v  /var/lib/containers/storage:/var/lib/containers/storage \
          quay.io/centos-bootc/bootc-image-builder:latest \
            --type vmdk \
            --rootfs ${{ env.FS_TYPE }} \
            --chown $(id -u):$(id -g) \
            --log-level debug \
            -vv \
            --use-librepo \
            ${{ env.REGISTRY }}/vm/${{ matrix.name }}:latest
        sudo mv ./output/${{ matrix.name }}/vmdk/disk.vmdk ./output/${{ env.IMAGE_PFX }}${{ matrix.name }}.vmdk

    - name: Generate OVF
      run: |
        VM_MANIFEST=$(jq -nc  \
          --arg disk_capacity "$(qemu-img info --output json ./output/${{ env.IMAGE_PFX }}${{ matrix.name }}.vmdk | jq -r '.["virtual-size"]')" \
          --arg disk_uuid "$(uuidgen)" \
          --arg machine_uuid "$(uuidgen)" \
            '{disk: {file: "${{ env.IMAGE_PFX }}${{ matrix.name }}.vmdk", capacity: $disk_capacity, uuid: $disk_uuid }, machine: { uuid: $machine_uuid } }')
        sudo apt update && sudo apt install -y jsonnet
        jsonnet -S \
          --tla-code args="$VM_MANIFEST" \
          config/vm.ovf.jsonnet > ./output/${{ env.IMAGE_PFX }}${{ matrix.name }}.ovf

    - name: Pack OVA
      working-directory: ./output
      run: |
        sha256sum --tag \
          ./${{ env.IMAGE_PFX }}${{ matrix.name }}.ovf \
          ./${{ env.IMAGE_PFX }}${{ matrix.name }}.vmdk \
          > ./${{ env.IMAGE_PFX }}${{ matrix.name }}.mf

        tar -cvf ${{ env.IMAGE_PFX }}${{ matrix.name }}.ova \
          ${{ env.IMAGE_PFX }}${{ matrix.name }}.ovf \
          ${{ env.IMAGE_PFX }}${{ matrix.name }}.vmdk \
          ${{ env.IMAGE_PFX }}${{ matrix.name }}.mf

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.IMAGE_PFX }}${{ matrix.name }}
        path: ./output/${{ env.IMAGE_PFX }}${{ matrix.name }}.ova
        archive: false
        if-no-files-found: error