name: Build
on:
  push:
    # branches:
      # - main

env:
  REGISTRY: ghcr.io/tao-ce/cozy

jobs:
  build:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build Image
      run: |
        sudo buildah build \
          -t ${{ env.REGISTRY }}/pi:latest \
          --build-arg FEDORA_FLAVOR=quay.io/fedora/fedora-bootc \
          --target base \
          --layers \
          .
        

    # - name: Build Image
    #   id: build-image
    #   uses: redhat-actions/buildah-build@v2
    #   with:
    #     image: ${{ env.REGISTRY }}/pi
    #     tags: latest ${{ github.sha }}
    #     containerfiles:
    #       ./Containerfile
    #     build-args: |
    #       FEDORA_VERSION=44
    #       FEDORA_FLAVOR=quay.io/fedora/fedora-bootc
    #     extra-args: |
    #       --target base

    # - name: Push Image
    #   uses: redhat-actions/push-to-registry@v2
    #   with:
    #     image: ${{ steps.build-image.outputs.image }}
    #     tags: ${{ steps.build-image.outputs.tags }}
    #     username: ${{ github.actor }}
    #     password: ${{ github.token }}
    #     registry: ghcr.io/${{ github.repository_owner }}
    #     extra-args: |
    #       --disable-content-trust

    # - name: Login registry
    #   uses: redhat-actions/podman-login@main
    #   with:
    #     username: ${{ github.actor }}
    #     password: ${{ github.token }}
    #     registry: ghcr.io/${{ github.repository_owner }}

    - name: Build Pi Image
      id: build-pi-image
      uses: osbuild/bootc-image-builder-action@main
      with:
        config-file: ./config/bootc.toml
        image: ${{ env.REGISTRY }}/pi:latest
        types: |
          raw
        rootfs: xfs

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pi-image
        path: ${{ steps.build-pi-image.outputs.output-directory }}
        if-no-files-found: error