name: Build Raspberry Pi 4 Image
on:
  push:
    branches:
      - main
      - build/**
    paths:
      - config/bootc.rpi4.toml
      - config/images.common.lst
      - config/images.rpi4.lst
      - config/packages.common.lst
      - config/packages.rpi4.lst
      - root/**
      - Containerfile
      - .github/workflows/build-rpi4.yaml

env:
  REGISTRY: ghcr.io/tao-ce/cozy
  FS_TYPE: btrfs
  FEDORA_VERSION: "44"

jobs:
  build:
    strategy:
      matrix:
        include:
        - fedora_flavor: quay.io/fedora/fedora-bootc
          name: lite
        # - fedora_flavor: quay.io/fedora-ostree-desktops/kinoite
          # name: kde
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Tar as root (setuid bit)
      run: |
        sudo chmod u+s /usr/bin/tar

    - name: Checkout code
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Setup cache
      uses: actions/cache@v5
      with:
        path: /var/lib/containers/storage
        key: ${{ runner.os }}-${{ runner.arch }}-containers-storage

    - name: Build Image
      run: |
        sudo buildah build \
          -t ${{ env.REGISTRY }}/rpi4/${{ matrix.name }}:latest \
          --build-arg FEDORA_FLAVOR=${{ matrix.fedora_flavor }} \
          --build-arg FEDORA_VERSION=${{ env.FEDORA_VERSION }} \
          --build-arg MEDIUM=rpi4 \
          --target appliance \
          --network=host \
          .

    - name: Build Pi Image
      run: |
        mkdir -p output/${{ matrix.name }}
        sudo podman run \
          --rm \
          -it \
          --privileged \
          --security-opt label=type:unconfined_t \
          -v ./config/bootc.rpi4.toml:/config.toml:ro \
          -v ./output/${{ matrix.name }}:/output \
          -v  /var/lib/containers/storage:/var/lib/containers/storage \
          quay.io/centos-bootc/bootc-image-builder:latest \
            --type raw \
            --rootfs ${{ env.FS_TYPE }} \
            --chown $(id -u):$(id -g) \
            --log-level debug \
            -vv \
            --use-librepo \
            ${{ env.REGISTRY }}/rpi4/${{ matrix.name }}:latest

    - name: Copy EFI Bootloader
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          libguestfs-tools
        [ "${{ env.FS_TYPE }}" = "btrfs" ] && ROOT_MOUNT_POINT="/:subvol=root" || ROOT_MOUNT_POINT="/"
        sudo guestfish \
          -m /dev/sda3:${ROOT_MOUNT_POINT} \
          -m /dev/sda2:/boot \
          -m /dev/sda1:/boot/efi \
          -a ./output/${{ matrix.name }}/image/disk.raw  <<EOF
        glob cp /ostree/boot.1/default/*/0/usr/share/uboot/rpi_arm64/u-boot.bin /boot/efi/rpi-u-boot.bin
        glob cp-a /ostree/boot.1/default/*/0/boot/efi/* /boot/efi/
        EOF

    - name: Compress Image
      run: |
        sudo ls -lh ./output/${{ matrix.name }}/image/disk.raw
        sudo xz -0 ./output/${{ matrix.name }}/image/disk.raw
        sudo ls -lh ./output/${{ matrix.name }}/image/disk.raw.xz
        sudo mv ./output/${{ matrix.name }}/image/disk.raw.xz ./output/rpi4-image-${{ matrix.name }}.raw.xz

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: rpi4-image-${{ matrix.name }}
        path: ./output/rpi4-image-${{ matrix.name }}.raw.xz
        archive: false
        if-no-files-found: error