name: Build VM Image
on:
  push:
    branches:
      - main
      - build/**
    paths:
      - config/bootc.vm.toml
      - config/images.common.lst
      - config/images.vm.lst
      - config/packages.common.lst
      - config/packages.vm.lst
      - root/**
      - Containerfile
      - .github/workflows/build-vm.yaml

env:
  REGISTRY: ghcr.io/tao-ce/cozy
  FS_TYPE: btrfs
  FEDORA_VERSION: "44"

jobs:
  build:
    strategy:
      matrix:
        include:
        - fedora_flavor: quay.io/fedora/fedora-bootc
          name: lite
        - fedora_flavor: quay.io/fedora-ostree-desktops/kinoite
          name: kde
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-24.04

    steps:
    - name: Tar as root (setuid bit)
      run: |
        sudo chmod u+s /usr/bin/tar

    - name: Checkout code
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Setup cache
      uses: actions/cache@v5
      with:
        path: /var/lib/containers/storage
        key: ${{ runner.os }}-${{ runner.arch }}-containers-storage

    - name: Build Image
      run: |
        sudo buildah build \
          -t ${{ env.REGISTRY }}/vm/${{ matrix.name }}:latest \
          --build-arg FEDORA_FLAVOR=${{ matrix.fedora_flavor }} \
          --build-arg FEDORA_VERSION=${{ env.FEDORA_VERSION }} \
          --build-arg FLAVOR=vm \
          --target appliance \
          --network=host \
          --layers \
          .

    - name: Build VM Image
      run: |
        mkdir -p output/${{ matrix.name }}
        sudo podman run \
          --rm \
          -it \
          --privileged \
          --security-opt label=type:unconfined_t \
          -v ./config/bootc.vm.toml:/config.toml:ro \
          -v ./output/${{ matrix.name }}:/output \
          -v  /var/lib/containers/storage:/var/lib/containers/storage \
          quay.io/centos-bootc/bootc-image-builder:latest \
            --type vmdk \
            --rootfs ${{ env.FS_TYPE }} \
            --chown $(id -u):$(id -g) \
            --log-level debug \
            -vv \
            --use-librepo \
            ${{ env.REGISTRY }}/vm/${{ matrix.name }}:latest
        sudo mv ./output/${{ matrix.name }}/image/disk.vmdk ./output/vm-image-${{ matrix.name }}.vmdk


    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: vm-image-${{ matrix.name }}
        path: ./output/vm-image-${{ matrix.name }}.vmdk
        archive: false
        if-no-files-found: error