name: Build
on:
  push:
    # branches:
      # - main

env:
  REGISTRY: ghcr.io/tao-ce/cozy

jobs:
  build:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Build Image
      run: |
        sudo buildah build \
          -t ${{ env.REGISTRY }}/pi:latest \
          --build-arg FEDORA_FLAVOR=quay.io/fedora/fedora-bootc \
          --build-arg FEDORA_VERSION=44 \
          --target pi \
          --layers \
          .

    - name: Build Pi Image
      run: |
        mkdir -p output
        sudo podman run \
          --rm \
          -it \
          --privileged \
          --security-opt label=type:unconfined_t \
          -v ./config/bootc.toml:/config.toml:ro \
          -v ./output:/output \
          -v  /var/lib/containers/storage:/var/lib/containers/storage \
          quay.io/centos-bootc/bootc-image-builder:latest \
            --type raw \
            --rootfs btrfs \
            --chown $(id -u):$(id -g) \
            --log-level debug \
            -vv \
            --use-librepo \
            ${{ env.REGISTRY }}/pi:latest

    - name: Copy EFI Bootloader
      run: |
        sudo apt-get install -y --no-install-recommends --no-install-suggests \
          libguestfs-tools
        sudo guestfish \
          -m /dev/sda3:/ \
          -m /dev/sda2:/boot \
          -m /dev/sda1:/boot/efi \
          -a ./output/image/disk.raw  <<EOF
        glob cp /ostree/boot.1/default/*/0/usr/share/uboot/rpi_arm64/u-boot.bin /boot/efi/rpi-u-boot.bin
        glob cp-a /ostree/boot.1/default/*/0/boot/efi/* /boot/efi/
        EOF

    - name: Compress Image
      run: |
        sudo xz -0 ./output/image/disk.raw

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: pi-image
        path: ./output/image/disk.raw.xz
        archive: false
        if-no-files-found: error