on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: The tag of the release
        required: true

env:
  PAGER: cat
  RELEASE_TAG: ${{ inputs.release-tag }}
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: write
  artifact-metadata: write
  actions: read

jobs:
  identify-workflows-runs:
    runs-on: ubuntu-24.04
    outputs:
      workflows-runs-ids: ${{ steps.identify-workflows-runs.outputs.workflows-runs-ids }}
    steps:
      - name: identify workflows runs
        id: identify-workflows-runs
        run: |
          tee -a "${GITHUB_OUTPUT}" <<EOF
          ::set-output name=workflows-runs-ids::$(gh run list \
            -R ${{ github.repository }} \
            -b ${{ env.RELEASE_TAG }} \
            --json databaseId \
            --jq '[.[].databaseId]' \
            -s success | jq -c . )
          EOF


  identify-artifacts:
    runs-on: ubuntu-24.04
    needs: [ identify-workflows-runs ]
    strategy:
      matrix:
        runId: ${{ fromJson(needs.identify-workflows-runs.outputs.workflows-runs-ids) }}
    steps:
      - name: identify artifacts
        id: identify-artifacts
        run: |
          gh api /repos/${{ github.repository }}/actions/runs/${{ matrix.runId }}/artifacts -q '[.artifacts[].id]|join(",")' \
            | sed \
              -e 's/^/ARTIFACTS_IDS=/' \
            | tee -a "${GITHUB_OUTPUT}"
          
      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{ steps.identify-artifacts.outputs.ARTIFACTS_IDS }}
          run-id: ${{ matrix.runId }}
          skip-decompress: true
          merge-multiple: true
          path: ./artifacts
          github-token: ${{ env.GH_TOKEN }}
          pattern: '*'


      - name: Upload to release
        uses: softprops/action-gh-release@v3
        with:
          files: ./artifacts/*

