on:
  release:
    types: [published]

env:
  PAGER: cat

permissions:
  contents: write
  artifact-metadata: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: identify workflows runs
        run: |
          gh run list \
            -R ${{ github.repository }} \
            -c $(git rev-parse  HEAD) \
            --json url,status,databaseId,name \
            -s completed > ./workflows-runs.json

      - name: identify artifacts
        id: identify-artifacts
        run: |
          jq . <workflows-runs.json | jq -r '.[].databaseId' > ./workflows-runs-ids.txt
          cat ./workflows-runs-ids.txt | while read id; do
            gh api /repos/${{ github.repository }}/actions/runs/$id/artifacts -q '.artifacts[].id'
          done  | tr '\n' ',' | sed s/^/ARTIFACTS_IDS=/ >>"${GITHUB_OUTPUT}"


      - name: Download Artifact
        uses: actions/download-artifact@v7
        with:
          artifact-ids: ${{ steps.identify-artifacts.outputs.ARTIFACTS_IDS }}
          skip-decompress: true
          merge-multiple: true
          path: ./artifacts

      - name: Upload to release
        uses: softprops/action-gh-release@v3
        with:
          files: ./artifacts/*

